name: Workflow D

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact from Workflow C
        uses: actions/download-artifact@v8
        with:
          name: timestamp-artifact-c
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: download-artifact

      - name: Rename and re-upload artifact
        env:
          TEST_KEY_A: ${{ secrets.TEST_KEY_A }}
        run: |
          mv download-artifact/timestamp-c.md timestamp-from-c.md
          cat timestamp-from-c.md

          D_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          if [ -z "$TEST_KEY_A" ]; then
            D_SECRET_STATUS="D key is empty"
          else
            D_SECRET_STATUS="D key is not empty"
          fi
          echo "$D_SECRET_STATUS"
          echo "" >> timestamp-from-c.md
          echo "D Timestamp: $D_TIMESTAMP" >> timestamp-from-c.md
          echo "$D_SECRET_STATUS" >> timestamp-from-c.md
          cat timestamp-from-c.md

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v7
        with:
          name: timestamp-artifact-from-c
          path: timestamp-from-c.md
