name: Workflow A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate timestamp and secret check file
        env:
          TEST_KEY_A: ${{ secrets.TEST_KEY_A }}
        run: |
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          if [ -z "$TEST_KEY_A" ]; then
            SECRET_STATUS="A key is empty"
          else
            SECRET_STATUS="A key is not empty"
          fi
          echo "$SECRET_STATUS"
          echo "Timestamp: $TIMESTAMP" > timestamp.md
          echo "$SECRET_STATUS" >> timestamp.md
          cat timestamp.md

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: timestamp-artifact
          path: timestamp.md
