name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact from Workflow A
        uses: actions/download-artifact@v8
        with:
          name: timestamp-artifact
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: download-artifact

      - name: Rename and re-upload artifact
        env:
          TEST_KEY_A: ${{ secrets.TEST_KEY_A }}
        run: |
          mv download-artifact/result-one.md timestamp-from-a.md
          cat timestamp-from-a.md

          B_TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          if [ -z "$TEST_KEY_A" ]; then
            B_SECRET_STATUS="B key is empty"
          else
            B_SECRET_STATUS="B key is not empty"
          fi
          echo "$B_SECRET_STATUS"
          echo "" >> timestamp-from-a.md
          echo "B Timestamp: $B_TIMESTAMP" >> timestamp-from-a.md
          echo "$B_SECRET_STATUS" >> timestamp-from-a.md
          cat timestamp-from-a.md

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v7
        with:
          name: timestamp-artifact-from-a
          path: timestamp-from-a.md
